### ISSUE TITLE
Gitsigns compatibility error

### ISSUE THREAD

**Issue by JA-Bar** [ahmedkhalf/jupyter-nvim#2]
Really looking forward to the development of this plugin, it looks great!

I've been playing around a bit and came across this error whenever I open any notebook:

```
Error executing vim.schedule lua callback: ...acker/start/plenary.nvim/lua/plenary/async_lib/async.lua:14: The coroutine failed with this message: Vim: E158: Invalid buffer name: 1
```
The error is coming from the gitsigns plugin, and it appears that the problem is that the original buffer is being deleted while gitsigns is running a coroutine refering to the deleted buffer's id. This could potentially be a problem with other plugins that use async to process the buffer being deleted.

I'm not familiar with plenary's async, but maybe the solution could be a way to await for coroutines to finish in `create_jupyter_buffer`.

**Comment by ahmedkhalf** [comment]
Thank you for your enthusiasm towards the project. I think this could a problem with other plugins too who process stuff after BufEnter autocmd... So what I'm gonna do is instead of having the auto-command be asynchronous it's gonna be synchronous which means it will freeze nvim for some time, this way it will never fire the BufEnter autocmd. But I'm gonna have to use some threding for it not to freeze so long. Thanks for pointing out the issue, I'l work on it later this afternoon.

**Comment by ahmedkhalf** [comment]
Problem fixed, please don't forget to update and use the `:UpdateRemotePlugins` command
